export default {
    FRONT_PAGE_LOADING: 'FRONT_PAGE_LOADING',
    FRONT_PAGE_ERROR: 'FRONT_PAGE_ERROR',
    GLOBAL_PAGE_LOADING: 'GLOBAL_PAGE_LOADING',
    GLOBAL_PAGE_ERROR: 'GLOBAL_PAGE_ERROR',
    SET_CUSTOMER_LIST: 'SET_CUSTOMER_LIST',
    SET_CUSTOMER_DETAIL: 'SET_CUSTOMER_DETAIL',
    SET_CATEGORY_LIST: 'SET_CATEGORY_LIST'
}